Merged revisions 364470 via svnmerge from file:///srv/subversion/repos/asterisk/team/rmudgett/ao2_enhancements
................
  r364470 | root | 2012-04-27 20:41:32 -0500 (Fri, 27 Apr 2012) | 51 lines
  
  Merged revisions 364436-364438,364444,364462 via svnmerge from 
  file:///srv/subversion/repos/asterisk/trunk
  
  ........
    r364436 | rmudgett | 2012-04-27 19:31:47 -0500 (Fri, 27 Apr 2012) | 10 lines
    
    PreDial - Ability to run dialplan on callee and caller channels before Dial.
    
    Thanks to Mark Murawski for the initial patch and feature definition.
    
    (closes issue ASTERISK-19548)
    Reported by: Mark Murawski
    
    Review: https://reviewboard.asterisk.org/r/1878/
    Review: https://reviewboard.asterisk.org/r/1229/
  ........
    r364437 | russell | 2012-04-27 19:58:54 -0500 (Fri, 27 Apr 2012) | 10 lines
    
    features: Add FEATURE() and FEATUREMAP() functions.
    
    Add two new dialplan functions: FEATURE() and FEATUREMAP().  FEATURE()
    lets you set some of the configuration options from the [general] section
    of features.conf on a per-channel basis.  FEATUREMAP() lets you customize
    the key sequence used to activate built-in features, such as blindxfer,
    and automon.  See the built-in documentation for details.
    
    Review: https://reviewboard.asterisk.org/r/1871/
  ........
    r364438 | russell | 2012-04-27 20:10:35 -0500 (Fri, 27 Apr 2012) | 6 lines
    
    app_minivm: Fix a couple compiler warnings.
    
    The warnings were about argv[0] being used uninitialized, which is correct.
    Just remove setting username to this value, since username is set again before
    it actually gets used.
  ........
    r364444 | russell | 2012-04-27 20:20:57 -0500 (Fri, 27 Apr 2012) | 2 lines
    
    res_corosync: Fix build against corosync 2.0.
  ........
    r364462 | russell | 2012-04-27 20:33:49 -0500 (Fri, 27 Apr 2012) | 8 lines
    
    md5: supress some compiler warnings.
    
    md5.c: In function ?\226?\128?\152MD5Final?\226?\128?\153:
    md5.c:154:2: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
    md5.c:155:2: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
    
    There is an md5 unit test and it still passes.
  ........
................