Merged revisions 164257,164268,164270,164272,164309,164312,164344,164349,164351,164415,164417,164419,164423,164428 via svnmerge from https://origsvn.digium.com/svn/asterisk/trunk
................
r164257 | file | 2008-12-15 08:41:22 -0700 (Mon, 15 Dec 2008) | 4 lines

Make app_fax compatible with newer versions of spandsp. This remains backwards compatible with earlier versions though so do not fret.
(closes issue #14073)
Reported by: seandarcy

................
r164268 | mmichelson | 2008-12-15 09:10:43 -0700 (Mon, 15 Dec 2008) | 17 lines

Fix up a few issues with regards to queues

* Fix reference counting used in the __queues_show function
* Add code to be sure that the "queue show" command does not
  print information for a realtime queue which has been deleted
  from the backend
* Add a missing unref to the realtime queue loading function for
  the case where a queue is in the module's container but has been
  deleted from the realtime backend

(closes issue #14033)
Reported by: cristiandimache
Patches:
      14033.patch uploaded by putnopvut (license 60)
Tested by: cristiandimache


................
r164270 | mmichelson | 2008-12-15 09:16:47 -0700 (Mon, 15 Dec 2008) | 4 lines

Fix a compile warning and a logic error that could have been bad
for non-realtime queues


................
r164272 | russell | 2008-12-15 09:17:55 -0700 (Mon, 15 Dec 2008) | 8 lines

When a reload is issued, always process the configuration for dundi.conf.

The reason is that a reload can be used to refresh DNS lookups for defined peers.
Even if the config file hasn't changed, we want to process it for that purpose.

(closes issue #13776)
Reported by: kombjuder

................
r164309 | russell | 2008-12-15 10:21:38 -0700 (Mon, 15 Dec 2008) | 2 lines

Fix a couple more build issues related to ast_str_opaque

................
r164312 | file | 2008-12-15 10:24:28 -0700 (Mon, 15 Dec 2008) | 4 lines

Use ast_seekstream to return the file stream back to the beginning instead of directly seeking to zero. This is because some audio formats have headers at the front that need to be skipped, which will be done by the format module.
(closes issue #14079)
Reported by: elguero

................
r164344 | file | 2008-12-15 10:46:32 -0700 (Mon, 15 Dec 2008) | 10 lines

Blocked revisions 164343 via svnmerge

........
  r164343 | file | 2008-12-15 13:43:59 -0400 (Mon, 15 Dec 2008) | 4 lines
  
  Use autoconf logic to determine whether the system has timersub or not. Do not blindly assume Solaris does not.
  (closes issue #13838)
  Reported by: ano
........

................
r164349 | tilghman | 2008-12-15 11:09:58 -0700 (Mon, 15 Dec 2008) | 4 lines

When querying for the structure of the CDR table, remove the schema, if it
exists.
(Closes issue #14058)

................
r164351 | file | 2008-12-15 11:12:24 -0700 (Mon, 15 Dec 2008) | 13 lines

Merged revisions 164350 via svnmerge from 
https://origsvn.digium.com/svn/asterisk/branches/1.4

........
  r164350 | file | 2008-12-15 14:11:21 -0400 (Mon, 15 Dec 2008) | 6 lines
  
  Do not try to unlock a non-existant channel if the transfer fails.
  (closes issue #13800)
  Reported by: dwagner
  Patches:
        asterisk-1.4.22-chan-sip-nullp.patch uploaded by tweety (license 608)
........

................
r164415 | murf | 2008-12-15 12:42:05 -0700 (Mon, 15 Dec 2008) | 16 lines

I was getting this warning during a compile
on a 64-bit machine running ubuntu server 8.10, 
and gcc-4.3.2:

   [CXXi] chan_vpb.ii -> chan_vpb.oo
cc1plus: warnings being treated as errors
In file included from /home/murf/asterisk/trunk/include/asterisk/utils.h:671,
                 from chan_vpb.cc:46:
/home/murf/asterisk/trunk/include/asterisk/strings.h: In function ‘char* ast_str_truncate(ast_str*, ssize_t)’:
/home/murf/asterisk/trunk/include/asterisk/strings.h:479: error: comparison between signed and unsigned integer expressions
make[1]: *** [chan_vpb.oo] Error 1
make: *** [channels] Error 2

which this fix silences


................
r164417 | tilghman | 2008-12-15 12:48:02 -0700 (Mon, 15 Dec 2008) | 3 lines

Revert ast_str opacity in chan_sip for now, since something wasn't quite right
in the merge.

................
r164419 | mmichelson | 2008-12-15 12:51:24 -0700 (Mon, 15 Dec 2008) | 12 lines

Merged revisions 164416 via svnmerge from 
https://origsvn.digium.com/svn/asterisk/branches/1.4

........
r164416 | mmichelson | 2008-12-15 13:45:07 -0600 (Mon, 15 Dec 2008) | 4 lines

Add notes to autoservice and pbx doxygen regarding a potential
deadlock scenario so that it is avoided in the future


........

................
r164423 | mmichelson | 2008-12-15 12:53:29 -0700 (Mon, 15 Dec 2008) | 11 lines

Merged revisions 164422 via svnmerge from 
https://origsvn.digium.com/svn/asterisk/branches/1.4

........
r164422 | mmichelson | 2008-12-15 13:53:08 -0600 (Mon, 15 Dec 2008) | 3 lines

Add the deadlock note to ast_spawn_extension as well


........

................
r164428 | mmichelson | 2008-12-15 13:07:03 -0700 (Mon, 15 Dec 2008) | 11 lines

Add an 'i' option to app_page. This option works the same as
the 'i' options for app_dial and app_queue, in that they will ignore
any attempts by phones to forward the call.

(closes issue #13977)
Reported by: putnopvut
Patches:
      page_ignore_forwards.patch uploaded by putnopvut (license 60)
Tested by: putnopvut, acunningham


................