Merged revisions 374643 via svnmerge from file:///srv/subversion/repos/asterisk/trunk
................
  r374643 | mjordan | 2012-10-07 19:45:36 -0500 (Sun, 07 Oct 2012) | 41 lines
  
  pjproject: Fix for Solaris builds. Do not undef s_addr.
  
  pjproject, in order to solve build problems on Windows [1], undefines s_addr in
  one of it's headers that is included in res_rtp_asterisk.c. On Solaris s_addr
  is not a structure member, but defined to map to the real strucuture member,
  therefore when building on Solaris it's possible to get build errors like:
  
      [CC] res_rtp_asterisk.c -> res_rtp_asterisk.o
      In file included from /export/home/admin/asterisk-11-svn/include/asterisk/stun.h:29,
                       from res_rtp_asterisk.c:51:
      /export/home/admin/asterisk-11-svn/include/asterisk/network.h: In function `inaddrcmp':
      /export/home/admin/asterisk-11-svn/include/asterisk/network.h:92: error: structure has no member named `s_addr'
      /export/home/admin/asterisk-11-svn/include/asterisk/network.h:92: error: structure has no member named `s_addr'
      res_rtp_asterisk.c: In function `ast_rtp_on_ice_tx_pkt':
      res_rtp_asterisk.c:706: warning: dereferencing type-punned pointer will break strict-aliasing rules
      res_rtp_asterisk.c:710: warning: dereferencing type-punned pointer will break strict-aliasing rules
      res_rtp_asterisk.c: In function `rtp_add_candidates_to_ice':
      res_rtp_asterisk.c:1085: error: structure has no member named `s_addr'
      make[2]: *** [res_rtp_asterisk.o] Error 1
      make[1]: *** [res] Error 2
      make[1]: Leaving directory `/export/home/admin/asterisk-11-svn'
      gmake: *** [_cleantest_all] Error 2
  
  Unfortunately, in order to make this work, I also had to make sure pjproject
  only used the typdef pj_in_addr and not the struct pj_in_addr so that when
  building Asterisk I could "typedef struct in_addr pj_in_addr". It's possible
  then that the library and users of those interfaces in Asterisk have a different
  idea about the type of the argument, while on the surface it looks like they are
  all 32 bit big endian values.
  
  [1] http://trac.pjsip.org/repos/changeset/484
  
  (issues ASTERISK-20366)
  Reported by: Ben Klang
  Tested by: Ben Klang, mjordan
  patches:
    0001-pjproject-Fix-for-Solaris-builds.-Do-not-undef-s.patch uploaded by Shaun Ruffell (license 5417)
  ........
  
  Merged revisions 374642 from http://svn.asterisk.org/svn/asterisk/branches/11
................