Merged revisions 292188 via svnmerge from https://origsvn.digium.com/svn/asterisk/branches/1.8
........
  r292188 | russell | 2010-10-18 14:50:04 -0500 (Mon, 18 Oct 2010) | 9 lines
  
  Resolve some compiler errors in ast_sockaddr_is_any().
  
  These errors came up once this function was used from within netsock2.c.
  The errors were like the following:
  
  netsock2.c:393: error: dereferencing pointer ‘({anonymous})’ does break strict-aliasing rules
  
  The usage of a union here avoids this problem.
........